baseURL = '/'
languageCode = 'en-us'
title = 'Olga Frolova'
theme = 'papermod'
profileMode = true
imageUrl = "images/Olga_Frolova_photo.png"

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Work with me"
url = "/work_with_me"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3


[params]

disableTwitterCards = true
ignoreLogs = ['warning-partial-superfluous-prefix']

[params.homeInfoParams]
    Title = "Welcome"
    Content = "Hi, Iâ€™m Olga Frolova - Customer Success & Technical Solutions Manager with 8+ years of experience leading enterprise post-sales strategy, technical adoption, and cross-functional initiatives for global clients. Skilled at bridging business and technical needs, building API-based solutions, and driving measurable growth. Passionate about enabling customers to succeed with cutting-edge technology, with proven experience at the intersection of project management, SaaS support, and digital workflows. I share my thoughts on LLMs, software development, and life in tech."

[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/olga-frolova/"
    icon = "fab fa-linkedin"
    iconColor = "#0077b5"

[[params.socialIcons]]
    name = "email"
    url = "mailto:olga.frolova.mail@gmail.com"
    icon = "fas fa-envelope"
    iconColor = "#0077b5"
[[params.socialIcons]]
name = "cv"
url = "/images/Olga_Frolova_2024.pdf"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

ignoreLogs = ['warning-partial-superfluous-prefix']
